// Autogenerated from Pigeon (v1.0.7), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import "pigeon.h"
#import <Flutter/Flutter.h>

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSDictionary<NSString *, id> *wrapResult(id result, FlutterError *error) {
  NSDictionary *errorDict = (NSDictionary *)[NSNull null];
  if (error) {
    errorDict = @{
        @"code": (error.code ? error.code : [NSNull null]),
        @"message": (error.message ? error.message : [NSNull null]),
        @"details": (error.details ? error.details : [NSNull null]),
        };
  }
  return @{
      @"result": (result ? result : [NSNull null]),
      @"error": errorDict,
      };
}

@interface DeviceInfoRequest ()
+ (DeviceInfoRequest *)fromMap:(NSDictionary *)dict;
- (NSDictionary *)toMap;
@end
@interface DeviceInfoReply ()
+ (DeviceInfoReply *)fromMap:(NSDictionary *)dict;
- (NSDictionary *)toMap;
@end

@implementation DeviceInfoRequest
+ (DeviceInfoRequest *)fromMap:(NSDictionary *)dict {
  DeviceInfoRequest *result = [[DeviceInfoRequest alloc] init];
  result.text = dict[@"text"];
  if ((NSNull *)result.text == [NSNull null]) {
    result.text = nil;
  }
  return result;
}
- (NSDictionary *)toMap {
  return [NSDictionary dictionaryWithObjectsAndKeys:(self.text ? self.text : [NSNull null]), @"text", nil];
}
@end

@implementation DeviceInfoReply
+ (DeviceInfoReply *)fromMap:(NSDictionary *)dict {
  DeviceInfoReply *result = [[DeviceInfoReply alloc] init];
  result.deviceInfoText = dict[@"deviceInfoText"];
  if ((NSNull *)result.deviceInfoText == [NSNull null]) {
    result.deviceInfoText = nil;
  }
  return result;
}
- (NSDictionary *)toMap {
  return [NSDictionary dictionaryWithObjectsAndKeys:(self.deviceInfoText ? self.deviceInfoText : [NSNull null]), @"deviceInfoText", nil];
}
@end

@interface DeviceInfoApiCodecReader : FlutterStandardReader
@end
@implementation DeviceInfoApiCodecReader
- (nullable id)readValueOfType:(UInt8)type 
{
  switch (type) {
    case 128:     
      return [DeviceInfoReply fromMap:[self readValue]];
    
    case 129:     
      return [DeviceInfoRequest fromMap:[self readValue]];
    
    default:    
      return [super readValueOfType:type];
    
  }
}
@end

@interface DeviceInfoApiCodecWriter : FlutterStandardWriter
@end
@implementation DeviceInfoApiCodecWriter
- (void)writeValue:(id)value 
{
  if ([value isKindOfClass:[DeviceInfoReply class]]) {
    [self writeByte:128];
    [self writeValue:[value toMap]];
  } else 
  if ([value isKindOfClass:[DeviceInfoRequest class]]) {
    [self writeByte:129];
    [self writeValue:[value toMap]];
  } else 
{
    [super writeValue:value];
  }
}
@end

@interface DeviceInfoApiCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation DeviceInfoApiCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[DeviceInfoApiCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[DeviceInfoApiCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *DeviceInfoApiGetCodec() {
  static dispatch_once_t s_pred = 0;
  static FlutterStandardMessageCodec *s_sharedObject = nil;
  dispatch_once(&s_pred, ^{
    DeviceInfoApiCodecReaderWriter *readerWriter = [[DeviceInfoApiCodecReaderWriter alloc] init];
    s_sharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return s_sharedObject;
}


void DeviceInfoApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<DeviceInfoApi> *api) {
  {
    FlutterBasicMessageChannel *channel =
      [FlutterBasicMessageChannel
        messageChannelWithName:@"dev.flutter.pigeon.DeviceInfoApi.fetchDeviceInfo"
        binaryMessenger:binaryMessenger
        codec:DeviceInfoApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(fetchDeviceInfoReq:error:)], @"DeviceInfoApi api (%@) doesn't respond to @selector(fetchDeviceInfoReq:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        DeviceInfoRequest *arg_req = args[0];
        FlutterError *error;
        DeviceInfoReply *output = [api fetchDeviceInfoReq:arg_req error:&error];
        callback(wrapResult(output, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
}
